### ISSUE TITLE
Does not work with angular 8

### ISSUE THREAD

**Issue by arturchyzy** [Pragmatists/ng-test-runner#16]
Assertions declared within verify(...) are not triggered during spec execution, 
`Spec '... has no expectations.`
But a following error is shown in console alfter tests execution:
```
An error was thrown in afterAll
Error: Expected '...' to equal '...'.
    at <Jasmine>
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/ng-test-runner/dist/test-utils.js:235:51
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/ng-test-runner/dist/test-utils.js:68:55
    at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:359:1)
```

**Comment by marmatys** [comment]
I've just publish [ng-test-runner-schematics](https://www.npmjs.com/package/ng-test-runner-schematics). Please check if it helps to setup your environment.

Here is setup that works for me
```
$  ng --version
...
Angular CLI: 8.0.1
Node: 10.12.0
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.1
@angular-devkit/core         8.0.1
@angular-devkit/schematics   8.0.1
@schematics/angular          8.0.1
@schematics/update           0.800.1
rxjs                         6.4.0
```
```
$ ng new angular80
...
added 1079 packages from 1058 contributors and audited 19008 packages in 53.173s
found 0 vulnerabilities
...
    Successfully initialized git.
$ cd angular80
$ ng add ng-test-runner-schematics
Installing packages for tooling via npm.
+ ng-test-runner-schematics@0.0.1
added 32 packages from 24 contributors and audited 31929 packages in 10.251s
found 0 vulnerabilities

Installed packages for tooling via npm.
UPDATE package.json (1355 bytes)
...

$ ng g ng-test-runner-schematics:ngc --name=first
CREATE src/app/first/first.component.css (0 bytes)
CREATE src/app/first/first.component.html (24 bytes)
CREATE src/app/first/first.component.ts (265 bytes)
CREATE src/app/first/first.component.spec.ts (503 bytes)
UPDATE src/app/app.module.ts (392 bytes)

$ npm test

> angular80@0.0.0 test /Users/marmatys/Projects/angular80
> ng test

 25% building 20/20 modules 0 active06 06 2019 01:19:48.594:WARN [karma]: No captured browser, open http://localhost:9876/
06 06 2019 01:19:48.899:INFO [karma-server]: Karma v4.1.0 server started at http://0.0.0.0:9876/
06 06 2019 01:19:48.900:INFO [launcher]: Launching browsers Chrome with concurrency unlimited
 25% building 91/91 modules 0 active06 06 2019 01:19:49.179:INFO [launcher]: Starting browser Chrome
06 06 2019 01:19:55.492:WARN [karma]: No captured browser, open http://localhost:9876/
06 06 2019 01:19:55.961:INFO [Chrome 75.0.3770 (Mac OS X 10.14.4)]: Connected on socket X4f8CNoSXQjPj10LAAAA with id 87782989
Chrome 75.0.3770 (Mac OS X 10.14.4): Executed 4 of 4 SUCCESS (0.157 secs / 0.131 secs)
TOTAL: 4 SUCCESS
TOTAL: 4 SUCCESS
```

**Comment by arturchyzy** [comment]
Ok, my bad. Missed required `async`.
